package com.example

import com.example.util.*
import org.junit.Assert.*
import org.junit.Test

class BarcodeGeneratorTest {

    @Test
    fun testCode128Validation() {
        val valid = BarcodeGenerator.validate("SKU-10025-A", BarcodeType.CODE_128)
        assertTrue(valid.isValid)
        assertEquals("SKU-10025-A", valid.normalizedValue)

        val empty = BarcodeGenerator.validate("   ", BarcodeType.CODE_128)
        assertFalse(empty.isValid)
    }

    @Test
    fun testEan13ValidationAndChecksum() {
        // Known valid EAN-13: 8901234567890 -> Checksum for 890123456789 is 0
        // Let's test 12 digits: "400638133393" -> 13th digit should be 1
        val check = BarcodeGenerator.calculateMod10Checksum("400638133393", weightOdd = 1, weightEven = 3)
        assertEquals(1, check)

        val autoCompleted = BarcodeGenerator.validate("400638133393", BarcodeType.EAN_13)
        assertTrue(autoCompleted.isValid)
        assertEquals("4006381333931", autoCompleted.normalizedValue)

        val fullValid = BarcodeGenerator.validate("4006381333931", BarcodeType.EAN_13)
        assertTrue(fullValid.isValid)

        // Corrupted checksum: "4006381333939"
        val corrupted = BarcodeGenerator.validate("4006381333939", BarcodeType.EAN_13)
        assertFalse(corrupted.isValid)
        assertNotNull(corrupted.errorMessage)
    }

    @Test
    fun testEan8ValidationAndChecksum() {
        // EAN-8: 7 digits auto-computes 8th digit
        val check = BarcodeGenerator.calculateMod10Checksum("9638507", weightOdd = 3, weightEven = 1)
        assertEquals(4, check)

        val result = BarcodeGenerator.validate("9638507", BarcodeType.EAN_8)
        assertTrue(result.isValid)
        assertEquals("96385074", result.normalizedValue)

        val fullValid = BarcodeGenerator.validate("96385074", BarcodeType.EAN_8)
        assertTrue(fullValid.isValid)

        val invalid = BarcodeGenerator.validate("96385079", BarcodeType.EAN_8)
        assertFalse(invalid.isValid)
    }

    @Test
    fun testUpcAValidationAndChecksum() {
        // UPC-A: 11 digits: "01234567890" -> 12th digit is 5
        val check = BarcodeGenerator.calculateMod10Checksum("01234567890", weightOdd = 3, weightEven = 1)
        assertEquals(5, check)

        val result = BarcodeGenerator.validate("01234567890", BarcodeType.UPC_A)
        assertTrue(result.isValid)
        assertEquals("012345678905", result.normalizedValue)

        val fullValid = BarcodeGenerator.validate("012345678905", BarcodeType.UPC_A)
        assertTrue(fullValid.isValid)

        val wrong = BarcodeGenerator.validate("012345678902", BarcodeType.UPC_A)
        assertFalse(wrong.isValid)
    }

    @Test
    fun testCode39Validation() {
        val valid = BarcodeGenerator.validate("PROD-1024", BarcodeType.CODE_39)
        assertTrue(valid.isValid)
        assertEquals("PROD-1024", valid.normalizedValue)

        val lowercaseConverted = BarcodeGenerator.validate("prod-1024", BarcodeType.CODE_39)
        assertTrue(lowercaseConverted.isValid)
        assertEquals("PROD-1024", lowercaseConverted.normalizedValue)

        // Invalid characters for Code 39
        val invalid = BarcodeGenerator.validate("PROD@#1024", BarcodeType.CODE_39)
        assertFalse(invalid.isValid)
    }

    @Test
    fun testItf14Validation() {
        // ITF-14: 13 digits
        val check = BarcodeGenerator.calculateMod10Checksum("1001234567890", weightOdd = 3, weightEven = 1)
        assertEquals(2, check)

        val result = BarcodeGenerator.validate("1001234567890", BarcodeType.ITF_14)
        assertTrue(result.isValid)
        assertEquals("10012345678902", result.normalizedValue)
    }

    @Test
    fun testAutoGeneratedBarcodesAreValid() {
        BarcodeType.entries.forEach { type ->
            val code = BarcodeGenerator.autoGenerateBarcode(type, 105L)
            assertTrue("Generated code '$code' for $type should not be blank", code.isNotBlank())
            val validation = BarcodeGenerator.validate(code, type)
            assertTrue("Generated code '$code' for $type should be valid: ${validation.errorMessage}", validation.isValid)
        }
    }

    @Test
    fun testDetectBarcodeType() {
        assertEquals(BarcodeType.EAN_13, BarcodeGenerator.detectBarcodeType("8901234567890"))
        assertEquals(BarcodeType.UPC_A, BarcodeGenerator.detectBarcodeType("012345678905"))
        assertEquals(BarcodeType.EAN_8, BarcodeGenerator.detectBarcodeType("96385074"))
        assertEquals(BarcodeType.ITF_14, BarcodeGenerator.detectBarcodeType("10012345678902"))
        assertEquals(BarcodeType.QR_CODE, BarcodeGenerator.detectBarcodeType("https://sentrystore.pk"))
        assertEquals(BarcodeType.CODE_128, BarcodeGenerator.detectBarcodeType("SKU-9901-B"))
    }

    @Test
    fun testLabelPaperTypeGeometry() {
        // Thermal roll 50x25
        val thermal = LabelPaperType.THERMAL_50X25
        assertFalse(thermal.isSheet)
        assertEquals(1, thermal.labelsPerPage)
        assertEquals(50f, thermal.singleLabelWidthMm, 0.1f)
        assertEquals(25f, thermal.singleLabelHeightMm, 0.1f)

        // A4 24 labels (3x8)
        val a4 = LabelPaperType.A4_24_LABELS
        assertTrue(a4.isSheet)
        assertEquals(24, a4.labelsPerPage)
        assertEquals(3, a4.columns)
        assertEquals(8, a4.rows)
        assertTrue(a4.singleLabelWidthMm > 60f)
        assertTrue(a4.singleLabelHeightMm > 30f)
    }
}
